# Generated by Django 5.1.4 on 2024-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='total_seats',
            field=models.IntegerField(default=5),
        ),
    ]
