# Generated by Django 5.1.4 on 2025-01-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_train_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
